OPTIONS:
  location: "Bangkok" # default
  tz: "Asia/Bangkok" # default

RPC:
  delay: 4000 # default (Minimum 4000)
  timestamp:
      start: "2025-09-02T07:45:34.593Z"
      end: "2029-12-31T17:00:00.000Z"
  TwitchURL: "https://www.twitch.tv/4levy_z1"
  YoutubeURL: "https://www.youtube.com/@4levy"
  details:
    - "0nyx.wtf - {time:en:12}"
  state:
    - "⛧⛧⛧⛧⛧⛧"
  assetsLargeText:
    - "{ping} ms - {uptime:days}"
  assetsSmallText:
    - "AssetsSmallText"
  assetsLargeImage:
    - "https://i.pinimg.com/736x/2b/f3/54/2bf35424a5b4e1674321d24f49898e21.jpg"
  assetsSmallImage:
    - "none"
  buttonFirst:
    - label: "0nyx.wtf"
      url: "https://0nyx.wtf/"
  buttonSecond:
    - label: "[ Server ]"
      url: "https://0nyx.wtf/"
 
INPUTS:
  activity:
    type: "LISTENING"
